services:
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: fadjrir
    ports:
     - "3306:3306"
    volumes:
     - mariadb_data:/var/lib/mysql
     - ./mariadb-init:/docker-entrypoint-initdb.d
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

volumes:
  mariadb_data:
